"""empty message

Revision ID: a56cb4e3eff9
Revises: 81334697f98f
Create Date: 2024-09-23 16:26:11.018670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56cb4e3eff9'
down_revision = '81334697f98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Blogs')
    # ### end Alembic commands ###
